# This file is used by your post processor (KUKA_KRC2)
# to generate the appropriate file for your robot.
# You will find your robot program in the same folder where this file is located.
# To avoid showing this file after program generation you can select:
#   Tools->Options->tab Other , then, uncheck "Show programs in Notepad"

import sys
import os
sys.path.append(os.path.abspath(r"""C:/RoboDK/Posts/""")) # temporarily add path to POSTS folder

from KUKA_KRC2 import *

def p(xyzrpw):
  x,y,z,r,p,w = xyzrpw
  a = r*math.pi/180.0
  b = p*math.pi/180.0
  c = w*math.pi/180.0
  ca = math.cos(a)
  sa = math.sin(a)
  cb = math.cos(b)
  sb = math.sin(b)
  cc = math.cos(c)
  sc = math.sin(c)
  return Mat([[cb*ca,ca*sc*sb-cc*sa,sc*sa+cc*ca*sb,x],[cb*sa,cc*ca+sc*sb*sa,cc*sb*sa-ca*sc,y],[-sb,cb*sc,cc*cb,z],[0.0,0.0,0.0,1.0]])

def make_program():
  print('Total instructions: 3')
  r = RobotPost(r"""KUKA_KRC2""",r"""KUKA KR 3 R540""",6,axes_type=['R','R','R','R','R','R'])

  r.ProgStart(r"""Prog1""")
  r.RunMessage(r"""Program generated by RoboDK v3.8.3 for KUKA KR 3 R540 on 27/06/2019 19:27:51""", True)
  r.RunMessage(r"""Using nominal kinematics.""", True)
  r.setFrame(p([0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000]),2,r"""Frame 2""")
  r.MoveJ(p([305.730307,-985.168253,453.607456,176.055923,5.789015,154.871309]),[3.177323,-83.447436,106.206200,-28.095719,64.030367,12.315809],[0.0,0.0,0.0])
  r.MoveJ(p([305.730307,-985.168253,453.607456,176.055923,5.789015,-167.644335]),[-5.976489,-82.970466,104.439890,14.472781,65.687162,-16.204626],[0.0,0.0,0.0])
  r.MoveJ(p([305.730307,-985.168253,453.607456,176.055923,5.789015,-137.219277]),[-12.266929,-79.602114,104.743515,43.405387,78.291252,-32.917915],[0.0,0.0,0.0])
  r.ProgFinish(r"""Prog1""")
  r.ProgSave(r"""C:/Users/Администратор/Desktop""",r"""Prog1""",False,False)
  r.ProgSendRobot("192.168.125.2", "C:/KukaShared", "anonymous", "")

if __name__ == "__main__":
  make_program()

